# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = clipper_python

HEADERS = \
   $$PWD/src/bindings/numpy_helper.h \
   $$PWD/src/bindings/symops.h \
   $$PWD/src/bindings/type_conversions.h \
   $$PWD/src/bindings/unit_cell.h \
   $$PWD/src/bindings/wrap_rtop_base.h \
   $$PWD/src/deps/clipper/ccp4/ccp4_map_io.h \
   $$PWD/src/deps/clipper/ccp4/ccp4_mtz_io.h \
   $$PWD/src/deps/clipper/ccp4/ccp4_mtz_types.h \
   $$PWD/src/deps/clipper/ccp4/ccp4_utils.h \
   $$PWD/src/deps/clipper/cctbx/clipper_cctbx.h \
   $$PWD/src/deps/clipper/cif/cif_data_io.h \
   $$PWD/src/deps/clipper/cns/cns_hkl_io.h \
   $$PWD/src/deps/clipper/cns/cns_map_io.h \
   $$PWD/src/deps/clipper/contrib/convolution_search.h \
   $$PWD/src/deps/clipper/contrib/edcalc.h \
   $$PWD/src/deps/clipper/contrib/fffear.h \
   $$PWD/src/deps/clipper/contrib/function_object_bases.h \
   $$PWD/src/deps/clipper/contrib/mapfilter.h \
   $$PWD/src/deps/clipper/contrib/originmatch.h \
   $$PWD/src/deps/clipper/contrib/sfcalc.h \
   $$PWD/src/deps/clipper/contrib/sfcalc_obs.h \
   $$PWD/src/deps/clipper/contrib/sfscale.h \
   $$PWD/src/deps/clipper/contrib/sfweight.h \
   $$PWD/src/deps/clipper/contrib/skeleton.h \
   $$PWD/src/deps/clipper/contrib/test_contrib.h \
   $$PWD/src/deps/clipper/core/atomsf.h \
   $$PWD/src/deps/clipper/core/cell.h \
   $$PWD/src/deps/clipper/core/clipper_instance.h \
   $$PWD/src/deps/clipper/core/clipper_memory.h \
   $$PWD/src/deps/clipper/core/clipper_message.h \
   $$PWD/src/deps/clipper/core/clipper_precision.h \
   $$PWD/src/deps/clipper/core/clipper_stats.h \
   $$PWD/src/deps/clipper/core/clipper_sysdep.h \
   $$PWD/src/deps/clipper/core/clipper_test.h \
   $$PWD/src/deps/clipper/core/clipper_thread.h \
   $$PWD/src/deps/clipper/core/clipper_types.h \
   $$PWD/src/deps/clipper/core/clipper_util.h \
   $$PWD/src/deps/clipper/core/container.h \
   $$PWD/src/deps/clipper/core/container_hkl.h \
   $$PWD/src/deps/clipper/core/container_map.h \
   $$PWD/src/deps/clipper/core/container_types.h \
   $$PWD/src/deps/clipper/core/coords.h \
   $$PWD/src/deps/clipper/core/derivs.h \
   $$PWD/src/deps/clipper/core/fftmap.h \
   $$PWD/src/deps/clipper/core/fftmap_sparse.h \
   $$PWD/src/deps/clipper/core/hkl_compute.h \
   $$PWD/src/deps/clipper/core/hkl_data.h \
   $$PWD/src/deps/clipper/core/hkl_datatypes.h \
   $$PWD/src/deps/clipper/core/hkl_info.h \
   $$PWD/src/deps/clipper/core/hkl_lookup.h \
   $$PWD/src/deps/clipper/core/hkl_operators.h \
   $$PWD/src/deps/clipper/core/map_interp.h \
   $$PWD/src/deps/clipper/core/map_utils.h \
   $$PWD/src/deps/clipper/core/nxmap.h \
   $$PWD/src/deps/clipper/core/nxmap_operator.h \
   $$PWD/src/deps/clipper/core/ramachandran.h \
   $$PWD/src/deps/clipper/core/resol_basisfn.h \
   $$PWD/src/deps/clipper/core/resol_fn.h \
   $$PWD/src/deps/clipper/core/resol_targetfn.h \
   $$PWD/src/deps/clipper/core/rotation.h \
   $$PWD/src/deps/clipper/core/spacegroup.h \
   $$PWD/src/deps/clipper/core/spacegroup_data.h \
   $$PWD/src/deps/clipper/core/symop.h \
   $$PWD/src/deps/clipper/core/test_core.h \
   $$PWD/src/deps/clipper/core/test_data.h \
   $$PWD/src/deps/clipper/core/xmap.h \
   $$PWD/src/deps/clipper/examples/cns2mtz.h \
   $$PWD/src/deps/clipper/minimol/container_minimol.h \
   $$PWD/src/deps/clipper/minimol/minimol.h \
   $$PWD/src/deps/clipper/minimol/minimol_data.h \
   $$PWD/src/deps/clipper/minimol/minimol_io.h \
   $$PWD/src/deps/clipper/minimol/minimol_seq.h \
   $$PWD/src/deps/clipper/minimol/minimol_utils.h \
   $$PWD/src/deps/clipper/mmdb/clipper_mmdb.h \
   $$PWD/src/deps/clipper/mmdbold/clipper_mmdb.h \
   $$PWD/src/deps/clipper/mmdbold/clipper_mmdb_types.h \
   $$PWD/src/deps/clipper/mmdbold/clipper_mmdb_wrapper.h \
   $$PWD/src/deps/clipper/mmdbold/container_mmdb.h \
   $$PWD/src/deps/clipper/mtz/map_io.h \
   $$PWD/src/deps/clipper/mtz/mtz_io.h \
   $$PWD/src/deps/clipper/mtz/mtz_types.h \
   $$PWD/src/deps/clipper/phs/phs_io.h \
   $$PWD/src/deps/clipper/clipper-ccp4.h \
   $$PWD/src/deps/clipper/clipper-cctbx.h \
   $$PWD/src/deps/clipper/clipper-cif.h \
   $$PWD/src/deps/clipper/clipper-cns.h \
   $$PWD/src/deps/clipper/clipper-contrib.h \
   $$PWD/src/deps/clipper/clipper-minimol.h \
   $$PWD/src/deps/clipper/clipper-mmdb.h \
   $$PWD/src/deps/clipper/clipper-mmdbold.h \
   $$PWD/src/deps/clipper/clipper-phs.h \
   $$PWD/src/deps/clipper/clipper.h \
   $$PWD/src/deps/clipper/config.h \
   $$PWD/src/deps/clipper/imex.h \
   $$PWD/src/deps/clipper/minimal-clipper-hkl.h \
   $$PWD/src/deps/clipper/minimal-clipper-map.h \
   $$PWD/src/deps/fftw2/include/fftw.h \
   $$PWD/src/deps/fftw2/include/rfftw.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_array.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_errno.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_file_err.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_fortran.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_general.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_parser.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_program.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_spg.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_sysdep.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_types.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_unitcell.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_utils.h \
   $$PWD/src/deps/libccp4/ccp4/ccp4_vars.h \
   $$PWD/src/deps/libccp4/ccp4/cmap_data.h \
   $$PWD/src/deps/libccp4/ccp4/cmap_errno.h \
   $$PWD/src/deps/libccp4/ccp4/cmap_header.h \
   $$PWD/src/deps/libccp4/ccp4/cmap_labels.h \
   $$PWD/src/deps/libccp4/ccp4/cmap_skew.h \
   $$PWD/src/deps/libccp4/ccp4/cmap_stats.h \
   $$PWD/src/deps/libccp4/ccp4/cmaplib.h \
   $$PWD/src/deps/libccp4/ccp4/cmaplib_f.h \
   $$PWD/src/deps/libccp4/ccp4/cmtzlib.h \
   $$PWD/src/deps/libccp4/ccp4/csymlib.h \
   $$PWD/src/deps/libccp4/ccp4/cvecmat.h \
   $$PWD/src/deps/libccp4/ccp4/imex.h \
   $$PWD/src/deps/libccp4/ccp4/library_file.h \
   $$PWD/src/deps/libccp4/ccp4/mtzdata.h \
   $$PWD/src/deps/libccp4/ccp4/overview.h \
   $$PWD/src/deps/libccp4/ccp4/pack_c.h \
   $$PWD/src/deps/libccp4/ccp4/w32mvs.h \
   $$PWD/src/deps/libccp4/fortran/binsort.h \
   $$PWD/src/deps/libccp4/config.h \
   $$PWD/src/deps/mmdb2/mmdb2/hybrid_36.h \
   $$PWD/src/deps/mmdb2/mmdb2/imex.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_atom.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_bondmngr.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_chain.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_cifdefs.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_coormngr.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_cryst.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_defs.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_ficif.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_io_file.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_io_stream.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_machine_.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_manager.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_mask.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_align.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_bfgsmin.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_fft.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_graph.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_linalg.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_rand.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_mattype.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_mmcif_.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_model.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_root.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_rwbrook.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_selmngr.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_seqsuperpose.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_symop.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_tables.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_title.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_uddata.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_utils.h \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_xml_.h \
   $$PWD/src/deps/mmdb2/config.h

SOURCES = \
   $$PWD/src/bindings/contrib/wrap_convolution_search.cpp \
   $$PWD/src/bindings/contrib/wrap_edcalc.cpp \
   $$PWD/src/bindings/contrib/wrap_fffear.cpp \
   $$PWD/src/bindings/contrib/wrap_mapfilter.cpp \
   $$PWD/src/bindings/contrib/wrap_originmatch.cpp \
   $$PWD/src/bindings/contrib/wrap_sfcalc.cpp \
   $$PWD/src/bindings/contrib/wrap_sfcalc_obs.cpp \
   $$PWD/src/bindings/contrib/wrap_sfscale.cpp \
   $$PWD/src/bindings/contrib/wrap_sfweight.cpp \
   $$PWD/src/bindings/contrib/wrap_skeleton.cpp \
   $$PWD/src/bindings/_clipper.cpp \
   $$PWD/src/bindings/clipper_pybind11.cpp \
   $$PWD/src/bindings/wrap_atomsf.cpp \
   $$PWD/src/bindings/wrap_ccp4_io.cpp \
   $$PWD/src/bindings/wrap_ccp4_map_io.cpp \
   $$PWD/src/bindings/wrap_ccp4_mtz_io.cpp \
   $$PWD/src/bindings/wrap_cell.cpp \
   $$PWD/src/bindings/wrap_clipper_stats.cpp \
   $$PWD/src/bindings/wrap_clipper_types.cpp \
   $$PWD/src/bindings/wrap_clipper_util.cpp \
   $$PWD/src/bindings/wrap_containers.cpp \
   $$PWD/src/bindings/wrap_coords.cpp \
   $$PWD/src/bindings/wrap_derivs.cpp \
   $$PWD/src/bindings/wrap_hkl_data.cpp \
   $$PWD/src/bindings/wrap_hkl_datatypes.cpp \
   $$PWD/src/bindings/wrap_hkl_info.cpp \
   $$PWD/src/bindings/wrap_interpolate.cpp \
   $$PWD/src/bindings/wrap_map_utils.cpp \
   $$PWD/src/bindings/wrap_nxmap.cpp \
   $$PWD/src/bindings/wrap_nxmap_operator.cpp \
   $$PWD/src/bindings/wrap_spacegroup.cpp \
   $$PWD/src/bindings/wrap_symop.cpp \
   $$PWD/src/bindings/wrap_symops.cpp \
   $$PWD/src/bindings/wrap_unit_cell.cpp \
   $$PWD/src/bindings/wrap_xmap.cpp \
   $$PWD/src/deps/clipper/ccp4/ccp4_map_io.cpp \
   $$PWD/src/deps/clipper/ccp4/ccp4_mtz_io.cpp \
   $$PWD/src/deps/clipper/ccp4/ccp4_mtz_types.cpp \
   $$PWD/src/deps/clipper/ccp4/ccp4_utils.cpp \
   $$PWD/src/deps/clipper/cctbx/clipper_cctbx.cpp \
   $$PWD/src/deps/clipper/cif/cif_data_io.cpp \
   $$PWD/src/deps/clipper/cns/cns_hkl_io.cpp \
   $$PWD/src/deps/clipper/cns/cns_map_io.cpp \
   $$PWD/src/deps/clipper/contrib/convolution_search.cpp \
   $$PWD/src/deps/clipper/contrib/edcalc.cpp \
   $$PWD/src/deps/clipper/contrib/fffear.cpp \
   $$PWD/src/deps/clipper/contrib/function_object_bases.cpp \
   $$PWD/src/deps/clipper/contrib/mapfilter.cpp \
   $$PWD/src/deps/clipper/contrib/originmatch.cpp \
   $$PWD/src/deps/clipper/contrib/sfcalc.cpp \
   $$PWD/src/deps/clipper/contrib/sfcalc_obs.cpp \
   $$PWD/src/deps/clipper/contrib/sfscale.cpp \
   $$PWD/src/deps/clipper/contrib/sfweight.cpp \
   $$PWD/src/deps/clipper/contrib/skeleton.cpp \
   $$PWD/src/deps/clipper/contrib/test_contrib.cpp \
   $$PWD/src/deps/clipper/core/atomsf.cpp \
   $$PWD/src/deps/clipper/core/cell.cpp \
   $$PWD/src/deps/clipper/core/clipper_instance.cpp \
   $$PWD/src/deps/clipper/core/clipper_memory.cpp \
   $$PWD/src/deps/clipper/core/clipper_message.cpp \
   $$PWD/src/deps/clipper/core/clipper_stats.cpp \
   $$PWD/src/deps/clipper/core/clipper_test.cpp \
   $$PWD/src/deps/clipper/core/clipper_thread.cpp \
   $$PWD/src/deps/clipper/core/clipper_types.cpp \
   $$PWD/src/deps/clipper/core/clipper_util.cpp \
   $$PWD/src/deps/clipper/core/container.cpp \
   $$PWD/src/deps/clipper/core/container_hkl.cpp \
   $$PWD/src/deps/clipper/core/container_map.cpp \
   $$PWD/src/deps/clipper/core/container_types.cpp \
   $$PWD/src/deps/clipper/core/coords.cpp \
   $$PWD/src/deps/clipper/core/derivs.cpp \
   $$PWD/src/deps/clipper/core/fftmap.cpp \
   $$PWD/src/deps/clipper/core/fftmap_sparse.cpp \
   $$PWD/src/deps/clipper/core/hkl_compute.cpp \
   $$PWD/src/deps/clipper/core/hkl_data.cpp \
   $$PWD/src/deps/clipper/core/hkl_datatypes.cpp \
   $$PWD/src/deps/clipper/core/hkl_info.cpp \
   $$PWD/src/deps/clipper/core/hkl_lookup.cpp \
   $$PWD/src/deps/clipper/core/hkl_operators.cpp \
   $$PWD/src/deps/clipper/core/map_interp.cpp \
   $$PWD/src/deps/clipper/core/map_utils.cpp \
   $$PWD/src/deps/clipper/core/nxmap.cpp \
   $$PWD/src/deps/clipper/core/nxmap_operator.cpp \
   $$PWD/src/deps/clipper/core/ramachandran.cpp \
   $$PWD/src/deps/clipper/core/resol_basisfn.cpp \
   $$PWD/src/deps/clipper/core/resol_fn.cpp \
   $$PWD/src/deps/clipper/core/resol_targetfn.cpp \
   $$PWD/src/deps/clipper/core/rotation.cpp \
   $$PWD/src/deps/clipper/core/spacegroup.cpp \
   $$PWD/src/deps/clipper/core/spacegroup_data.cpp \
   $$PWD/src/deps/clipper/core/symop.cpp \
   $$PWD/src/deps/clipper/core/test_core.cpp \
   $$PWD/src/deps/clipper/core/test_data.cpp \
   $$PWD/src/deps/clipper/core/xmap.cpp \
   $$PWD/src/deps/clipper/examples/c2test.cpp \
   $$PWD/src/deps/clipper/examples/ccad.cpp \
   $$PWD/src/deps/clipper/examples/cctbxtest.cpp \
   $$PWD/src/deps/clipper/examples/ciftophs.cpp \
   $$PWD/src/deps/clipper/examples/cmaplocal.cpp \
   $$PWD/src/deps/clipper/examples/cns2mtz.cpp \
   $$PWD/src/deps/clipper/examples/cnstest.cpp \
   $$PWD/src/deps/clipper/examples/diffmap.cpp \
   $$PWD/src/deps/clipper/examples/ffttest.cpp \
   $$PWD/src/deps/clipper/examples/fomvar.cpp \
   $$PWD/src/deps/clipper/examples/ftndemo_lib.cpp \
   $$PWD/src/deps/clipper/examples/maketestdata.cpp \
   $$PWD/src/deps/clipper/examples/maphist.cpp \
   $$PWD/src/deps/clipper/examples/maptest.cpp \
   $$PWD/src/deps/clipper/examples/memtest.cpp \
   $$PWD/src/deps/clipper/examples/mmtest.cpp \
   $$PWD/src/deps/clipper/examples/mtzcut.cpp \
   $$PWD/src/deps/clipper/examples/mtziotest.cpp \
   $$PWD/src/deps/clipper/examples/mtzmissing.cpp \
   $$PWD/src/deps/clipper/examples/mtztest.cpp \
   $$PWD/src/deps/clipper/examples/octest.cpp \
   $$PWD/src/deps/clipper/examples/phstest.cpp \
   $$PWD/src/deps/clipper/examples/reftest.cpp \
   $$PWD/src/deps/clipper/examples/reftest2.cpp \
   $$PWD/src/deps/clipper/examples/rfltest.cpp \
   $$PWD/src/deps/clipper/examples/sftest.cpp \
   $$PWD/src/deps/clipper/examples/sgtest.cpp \
   $$PWD/src/deps/clipper/examples/sktest.cpp \
   $$PWD/src/deps/clipper/examples/symtest.cpp \
   $$PWD/src/deps/clipper/fortran/f_interface.cpp \
   $$PWD/src/deps/clipper/minimol/container_minimol.cpp \
   $$PWD/src/deps/clipper/minimol/minimol.cpp \
   $$PWD/src/deps/clipper/minimol/minimol_data.cpp \
   $$PWD/src/deps/clipper/minimol/minimol_io.cpp \
   $$PWD/src/deps/clipper/minimol/minimol_seq.cpp \
   $$PWD/src/deps/clipper/minimol/minimol_utils.cpp \
   $$PWD/src/deps/clipper/mmdb/clipper_mmdb.cpp \
   $$PWD/src/deps/clipper/mmdbold/clipper_mmdb.cpp \
   $$PWD/src/deps/clipper/mmdbold/clipper_mmdb_types.cpp \
   $$PWD/src/deps/clipper/mmdbold/clipper_mmdb_wrapper.cpp \
   $$PWD/src/deps/clipper/mmdbold/container_mmdb.cpp \
   $$PWD/src/deps/clipper/mtz/map_io.cpp \
   $$PWD/src/deps/clipper/mtz/mtz_io.cpp \
   $$PWD/src/deps/clipper/mtz/mtz_types.cpp \
   $$PWD/src/deps/clipper/phs/phs_io.cpp \
   $$PWD/src/deps/libccp4/ccp4/ccp4_array.c \
   $$PWD/src/deps/libccp4/ccp4/ccp4_general.c \
   $$PWD/src/deps/libccp4/ccp4/ccp4_parser.c \
   $$PWD/src/deps/libccp4/ccp4/ccp4_program.c \
   $$PWD/src/deps/libccp4/ccp4/ccp4_unitcell.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_accessor.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_close.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_data.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_header.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_labels.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_open.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_skew.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_stats.c \
   $$PWD/src/deps/libccp4/ccp4/cmap_symop.c \
   $$PWD/src/deps/libccp4/ccp4/cmtzlib.c \
   $$PWD/src/deps/libccp4/ccp4/csymlib.c \
   $$PWD/src/deps/libccp4/ccp4/cvecmat.c \
   $$PWD/src/deps/libccp4/ccp4/library_err.c \
   $$PWD/src/deps/libccp4/ccp4/library_file.c \
   $$PWD/src/deps/libccp4/ccp4/library_utils.c \
   $$PWD/src/deps/libccp4/ccp4/pack_c.c \
   $$PWD/src/deps/libccp4/ccp4/vmslibrary.c \
   $$PWD/src/deps/libccp4/ccp4/w32mvs.c \
   $$PWD/src/deps/libccp4/fortran/binsortint.c \
   $$PWD/src/deps/libccp4/fortran/ccp4_diskio_f.c \
   $$PWD/src/deps/libccp4/fortran/ccp4_general_f.c \
   $$PWD/src/deps/libccp4/fortran/ccp4_parser_f.c \
   $$PWD/src/deps/libccp4/fortran/ccp4_unitcell_f.c \
   $$PWD/src/deps/libccp4/fortran/cmaplib_f.c \
   $$PWD/src/deps/libccp4/fortran/cmtzlib_f.c \
   $$PWD/src/deps/libccp4/fortran/csymlib_f.c \
   $$PWD/src/deps/libccp4/fortran/libhtml_f.cpp \
   $$PWD/src/deps/libccp4/fortran/library_f.c \
   $$PWD/src/deps/libccp4/fortran/testlib_f.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/hybrid_36.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_atom.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_bondmngr.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_chain.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_cifdefs.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_coormngr.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_cryst.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_ficif.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_io_file.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_io_stream.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_machine_.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_manager.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_mask.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_align.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_bfgsmin.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_fft.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_graph.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_linalg.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_math_rand.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_mattype.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_mmcif_.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_model.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_root.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_rwbrook.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_selmngr.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_seqsuperpose.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_symop.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_tables.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_title.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_uddata.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_utils.cpp \
   $$PWD/src/deps/mmdb2/mmdb2/mmdb_xml_.cpp

INCLUDEPATH = \
    $$PWD/src/bindings \
    $$PWD/src/deps/clipper \
    $$PWD/src/deps/clipper/ccp4 \
    $$PWD/src/deps/clipper/cctbx \
    $$PWD/src/deps/clipper/cif \
    $$PWD/src/deps/clipper/cns \
    $$PWD/src/deps/clipper/contrib \
    $$PWD/src/deps/clipper/core \
    $$PWD/src/deps/clipper/examples \
    $$PWD/src/deps/clipper/minimol \
    $$PWD/src/deps/clipper/mmdb \
    $$PWD/src/deps/clipper/mmdbold \
    $$PWD/src/deps/clipper/mtz \
    $$PWD/src/deps/clipper/phs \
    $$PWD/src/deps/fftw2/include \
    $$PWD/src/deps/libccp4 \
    $$PWD/src/deps/libccp4/ccp4 \
    $$PWD/src/deps/libccp4/fortran \
    $$PWD/src/deps/mmdb2 \
    /dls/science/groups/i04-1/conor_dev/pybind11/include \
    $$PWD/src/deps/mmdb2/mmdb2

#DEFINES = 

